### PR TITLE
Fact file - database integration

### PR DESCRIPTION
**Pull request by jacksos101**
The fact files are now working with database data.

 - Carousel is running from images found using database data
 - I have turned on auto play for the carousel, we can tweak this later if desired.
 - Audio players are implemented for all audio buttons.
 - I have removed the scroll bar as it was showing horizontally when the carousel changed image.
 - I haven't implemented fact file nuggets into the view yet. We need to discuss how we want to do it.
 - Fact file details view is looking a bit flat, can be polished up later on.

### CODE REVIEW

**Comment by jacksos101** [comment]
The views here will still need to be made responsive also.

**Comment by jacksos101** [comment]
Fixes #14

**Comment by MitchellQ** [comment]
I had turned auto play off because it doesn't restart (to my knowledge) and since there is only going to be 3 images it ends up stopped quickly didnt think there was much point

**Comment by jacksos101** [comment]
Autoplay is cycling fine between two images.

**Pull request merged**
