### PR TITLE
Map - Database Integration

### PR DESCRIPTION
**Pull request by jacksos101**
This PR allows the map to display markers from the database.

Active track markers are distinguished from inactive.

Animation is smooth.

Animated move function fixed so that the zoom also animates.

### CODE REVIEW

**Comment by jacksos101** [comment]
Fixes #8

**Comment by jacksos101** [comment]
Yeah possibly

**Comment by jacksos101** [comment]
Possibly tapping an inactive tracks marker could also select that track?

**Comment by MitchellQ** [comment]
I suppose you could do that also, but the map shouldn't animate to the location if that is the case. however the icons should still remain the same as we could create a gulf of execution

**Pull request merged**
